name: wallet_proxy_pattern
description: Proxy wallet for Web and Mobile/Desktop platform.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.4
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2

  # UUID
  uuid: ^3.0.5

  # Cryptography
  cryptography: ^2.0.5

  # Hex
  convert: ^3.0.2

  # JSON Annotation
  json_annotation: ^4.4.0

  # Stack trace
  stack_trace: ^1.10.0

  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  floor: ^1.2.0
  flutter_secure_storage: ^5.1.0
  shared_preferences: ^2.0.15
  # url helper
  url_launcher: ^6.1.5
  async: ^2.4.1
  eth_sig_util: ^0.0.9
  decimal: ^2.3.0
  jiffy: ^5.0.0
  web3_provider: ^1.1.3
  flutter_web3: ^2.1.9
  web3dart: 2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.2
  floor_generator: ^1.2.0
  dart_code_metrics: ^4.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
